yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=400, blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(Group, blank=True,
                              null=True, on_delete=models.SET_NULL)

yatube/posts/views.py
# posts/views.py
from django.shortcuts import render
# Импортируем модель, чтобы обратиться к ней
from .models import Post, Group
from django.shortcuts import get_object_or_404


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <meta charset="utf-8">
    <!-- Загрузка статики -->
    <title> {% block title %}
        {% endblock %} </title>
</head>
<body>
    {% include 'includes/header.html' %}
    <main>
        <div class="container">
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock content %}
        </div>
    </main>
    {% include 'includes/footer.html' %}
</body>
</html>

yatube/templates/includes/footer.html
{% comment %} <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>     {% endcomment %}


   
<footer class="border-top text-center py-3">
    <p>© {% now "Y" %} Copyright 
      <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="posts/index.html">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
  </nav>
</header>

yatube/templates/includes/post_info.html
<ul>
    <li>
      Автор: {{ post.author }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d.m.Y" }}
    </li>
  </ul>

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title%} {{ group.title }} {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts %}
  <article>
    {% include 'includes/post_info.html' %}
    <p>{{ post.text }}</p>
  </article>
  {% if not forloop.last %}
  <hr />
  {% endif %} {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %} 
{% block title %} Последние обновления на сайте {% endblock %} 
{% block content %}
<div class="container py-5"> 
  <h1>Последние обновления на сайте</h1>
  {% for post in posts %}
  <article>
    {% include 'includes/post_info.html' %}
      <p style= "text-align:justify;text-indent: 1.5em";>{{ post.text }}</p>
    {% if post.group %}   
      <p style="text-align:left;"><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
    {% endif %}
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  <!-- под последним постом нет линии -->
</div>
{% endblock %}